remote_theme: noew/academic
title: Noé M. Wiener
author: Noé M. Wiener
description: Lecturer in Economics at the University of Massachusetts Amherst

baseurl: ""
url: "http://www.noewiener.com"

# Author

email: nwiener@umass.edu
github_username: noew
author_website: http://www.noewiener.com
curriculum:
  name: curriculum vitae
  url: https://umass-my.sharepoint.com/:b:/g/personal/nwiener_umass_edu/ERJb9EY0be9HkZoRY8tslTcBeBoY1DQ0W6rqlWO-DawT0g?e=XdCTMk
